spring:
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  application:
    name: cloud-native-spring
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
      health:
        show-details: always

info:
  build:
    name: @project.name@
    description: @project.description@
    version: @project.version@

greeting: "Local Hello "

---
spring:
  profiles: cloud

management:
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true

greeting: "Cloud Hello "
