spring:
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
      health:
        show-details: always

info:
  build:
    name: 'cloud-native-spring'
    description: 'A simple Cloud Native Spring application demonstrating Spring Boot'
    version: 1.0-SNAPSHOT



---
spring:
  profiles: cloud

management:
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true