spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: cloud-native-spring-ui

management:
  endpoints:
    web:
      exposure: 
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full

feign:
  hystrix:
    enabled: true

info: # add this section
  build:
    name: @application.name@
    description: @application.description@
    version: @application.version@

---
spring:
  profiles: cloud

management:
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true