spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: cloud-native-spring-ui

management:
  endpoints:
    web:
      exposure: 
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full

info: # add this section
  build:
    name: 'Cloud Native Spring (Front-end)'
    description: 'Spring Boot powered Vaadin UI that transacts the Cloud Native Spring (Back-end) to render a simple table of cities'
    version: 1.0-SNAPSHOT

---
spring:
  profiles: cloud

management:
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true
